package cl.onemarketer.enumerated;

public enum MensajesRespuestaRest {
	CREADO,
	NO_CREADO,
	CREACION_INCOMPLETA,
	NO_EXISTEN_ROLES,
	ERROR_INTERNO,
	USUARIOS_INCOMPLETOS,
	OK,
	NOK,
	NO_EXISTE,
	YA_EXISTE,
	DATOS_INCONSISTENTES,
	FALTAN_DATOS_RELACIONADOS,
	NO_HABILITADO,
	PETICION_NO_COMPLETADA,
	ACTUALIZADO,
	FINALIZADO,
	DUPLICADO,
	RENDICION_NO_VALIDA,
	NO_PRESENTA_CAMBIOS;	
}
